baseurl         = "/"
#theme           = "ananke"
theme           = "hugo-casper-two"
languageCode    = "it-IT"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Tennis Tavolo Morelli"
  subtitle    = "A.S.D. Cernusco Sul Naviglio"

  cover       = "images/hero_scuro.jpg"
  description = "Tennis Tavolo Morelli"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  # twitterName = "faketryghost"
  fbName = "tennistavolomorelli"
  # githubName = "eueung"

  logo = "images/logo-invertito.svg"
  orgName = "Tennis Tavolo Morelli"
  orgWebsite = "https://www.tennistavolomorelli.it"
  orgDescription = "Tennis Tavolo Morelli"

  # author = "EM"
  # authorAvatar = "img/ghost-icon.png"
  #authorLocation = "Bandung, ID"
  #authorWebsite = "https://eueung.github.io"
  # authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - pagina"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  posts = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Dove Siamo"
  url = "/dovesiamo"
  weight = 100

[[menu.main]]
  name = "Squadre"
  url = "/squadre"
  weight = 99

[[menu.main]]
  name = "Campionato"
  url = "/campionato"
  weight = 80


