---
label: Base
hide_body: false
fields:
- type: datetime
  name: date
  label: date
- type: text
  name: linktitle
  label: linktitle
- type: text
  name: title
  label: title
- type: number
  name: weight
  label: weight
- type: file
  name: image
  label: image
pages:
- content/post/notizia-dal-telefono.md
