---
label: Base
hide_body: false
fields:
- type: datetime
  name: date
  label: date
- type: text
  name: title
  label: title
- type: file
  name: image
  label: image
pages:
- content/post/titolo-interessante.md
