---
label: Base
hide_body: false
fields:
- type: text
  name: author
  label: author
- type: datetime
  name: date
  label: date
- type: text
  name: linktitle
  label: linktitle
- type: text
  name: next
  label: next
- type: text
  name: prev
  label: prev
- type: text
  name: title
  label: title
- type: number
  name: weight
  label: weight
- type: file
  name: authorAvatar
  label: authorAvatar
- type: file
  name: image
  label: image
